name = "FastConv"
uuid = "bfc4c9d6-058c-4b9f-a9f1-b3a56ed43392"
authors = ["Arthur E. B. P."]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
